config/routes.rb
Katalog::Application.routes.draw do |map|
  resources :thing_lists

  resources :departments

  devise_for :users,
    :path_names => { :sign_up => 'register', :sign_in => 'log_in' },
    :controllers => { :registrations => "users/registrations" }
  
  resources :things, :people, :groups, :kontexts, :study_modules
  
  match '/:id', :to => 'things#show'
  
  root :to => "things#index"
end

app/models/department.rb
class Department < ActiveRecord::Base
  
  attr_accessor :head_of_department_id
  before_save do |department|
    department.head_of_department = Person.find_by_id(head_of_department_id)
  end
  
  has_many :study_modules
  has_one :head_of_department, :class_name => 'Person'
  
  scope :asc, order('name')
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  has_many :credits, :dependent => :destroy
  has_many :people, :through => :credits
  accepts_nested_attributes_for :credits, :allow_destroy => true
  
  has_many :images, :as => :imageable, :dependent => :destroy
  accepts_nested_attributes_for :images, :allow_destroy => true
  
  belongs_to :user
  
  has_many :kontext_links, :as => :kontextable
  has_many :kontexts, :through => :kontext_links
  
  has_many :thing_list_items
  
  has_and_belongs_to_many :study_modules
  
  validates_presence_of :title, :description, :credits, :kind, :materials, 
    :license, :release_date
  validates_associated :credits, :images
  
  attr_accessible :title, :description, :credits_attributes, :images_attributes,
    :kontext_ids, :license, :kind, :materials, :dimensions_x, :dimensions_y,
    :dimensions_z, :dimensions_unit, :dimensions_additional, :release_date, 
    :start_date, :study_module_ids
  
  def dimensions
    result = [dimensions_x, dimensions_y, dimensions_z].compact.join('×')
    result += " #{dimensions_unit}" if dimensions_unit.present?
    result if result.present?
  end
  
  def tools
    self.credits.map(&:tools).uniq
  end
  
  scope :asc, order('title')
  scope :by_user, lambda { |user| where( :user_id.eq % user.id ) }
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  load_and_authorize_resource
  
  def index
    if params[:own] && user_signed_in?
      @things = Thing.by_user(current_user).asc
    else
      @things = Thing.asc
    end
  end
  
  def show
  end
  
  def new
    @thing.credits.build(:person => current_user.person)
  end
  
  def edit
  end
  
  def create
    @thing.user = current_user
    
    if @thing.save
      redirect_to @thing, :notice => 'Thing was successfully created.'
    else
      render :action => "new"
    end
  end
  
  def update
    params[:thing][:kontext_ids] ||= []
    @thing = Thing.find(params[:id], :include => [:credits,:images])
    
    if @thing.update_attributes(params[:thing])
      redirect_to @thing, :notice => 'Thing was successfully updated.'
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @thing.destroy
    redirect_to things_url, :notice => 'Thing destroyed.'
  end
end

app/helpers/things_helper.rb
module ThingsHelper
  
  def for_unique_people( thing, &block )
    thing.people.uniq.each do |person|
      credits = person.credits.where(:thing_id.eq % thing.id)
      roles = credits.map(&:role).to_sentence
      
      if block_given?
        yield person, roles
      else
        return
      end
    end
  end
  
end

app/views/things/_credit_fields.html.erb
<p class="fields">
  <%= f.collection_select(:person_id, Person.asc, :id, :full_name, {:prompt => ""}) %>
  <%= f.label :role, 'with role' %>
  <%= f.text_field :role, :size => 14 %><br />
  <%= f.label :tools, 'and tools' %>
  <%= f.text_field :tools, :size => 24 %>
  <%= link_to_remove_fields 'remove', f %>
</p>

app/views/things/_form.html.erb
<%= form_for(@thing, :html => {:multipart => true}) do |f| %>
  <% if @thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
      <% @thing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  
  <div class="field">
    <%= f.label :kind %><br />
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :materials %><br />
    <%= f.text_field :materials %>
  </div>
  <div class="field">
    <%= f.label :dimensions %><br />
    <%= f.text_field :dimensions_x, :size => 3 %> ×
    <%= f.text_field :dimensions_y, :size => 3 %> ×
    <%= f.text_field :dimensions_z, :size => 3 %> &nbsp;
    <%= f.text_field :dimensions_unit, :size => 3, :value => 'cm' %>
    (for example <em>10×10×50 cm</em> or <em>15 min</em>)<br />
    <%= f.text_field :dimensions_additional %> (additional info)
  </div>
  <div class="field">
    <%= f.label :release_date %><br />
    <%= f.date_select :release_date %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  
  Credits<br />
  <%= f.fields_for :credits do |builder| -%>
    <%= render 'credit_fields', :f => builder %>
  <% end -%>
  <p><%= link_to_add_fields 'add credit', f, :credits %></p>

  <div class="field">
    <%= f.label :study_module_ids, "Study Modules" %><br />
    <%= f.collection_select :study_module_ids, StudyModule.asc, :id, :name, { :selected => @thing.study_module_ids }, { :multiple => true, :name => 'thing[study_module_ids][]' } -%>
  </div>
  
  Images<br />
  <%= f.fields_for :images do |builder| -%>
    <%= render 'shared/image_fields', :f => builder %>
  <% end -%>
  <p><%= link_to_add_fields 'add image', f, :images, :shared => true %></p>
  
  <div class="field">
  Kontext<br />
  <ul>
    <%= render :partial    => 'kontext_checkboxes',
               :collection => Kontext.roots,
               :as         => :kontext,
               :locals     => { :f => f } %>
  </ul>
  </div>
  
  <div class="field">
    <%= f.label :license %><br />
    <%= f.text_field :license, :value => 'Copyright' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/things/_image_fields.html.erb
<p class="fields">
  <% unless f.object.new_record? -%>
    <%= image_tag f.object.data.url(:thumb) %>
  <% else -%>
    <%= f.label :data, 'Image — ' %>
    <%= f.file_field :data %>
  <% end -%>
  <!--<br />
  <%#= f.label :title %>
  <%#= f.text_field :title %>
  <br />
  <%#= f.label :description %>
  <%#= f.text_field :description %>
  -->
  <%= link_to_remove_fields 'remove', f %>
</p>

app/views/things/_kontext_checkboxes.html.erb
<li>
  <%= check_box_tag :kontext_ids, kontext.id,
    @thing.kontexts.include?(kontext),
    :id => "thing_kontext_ids_#{kontext.id}",
    :name => 'thing[kontext_ids][]' %>
    
  <%= f.label "kontext_ids_#{kontext.id}", kontext.name %><br />
  
  <% if kontext.children.any? -%>
    <ul>
      <%= render :partial    => 'kontext_checkboxes',
                 :collection => kontext.children,
                 :as         => :kontext,
                 :locals     => { :f => f } %>
    </ul>
  <% end -%>
</li>

app/views/things/edit.html.erb
<h1>Edit thing</h1>

<%= render 'form' %>

app/views/things/index.html.erb
<div id="controls" class="push_3">
	<% if can? :create, Thing -%>
		<%= link_to 'New thing', new_thing_path %>
	<% end -%>
</div>

<h1>Things</h1>

<div class="entry-content things-index">
	<% @things.each do |thing| %>
		<ul>
			<li class="meta"><%= thing.kind %></li>
			<li><%= link_to thing.title, thing %></li>
	
		</ul>
	<% end %>
</div>

app/views/things/new.html.erb
<h1>New thing</h1>

<%= render 'form' %>

app/views/things/show.html.erb
	<div id="controls">
		<% if can? :update, @thing -%>
			<%= link_to 'Edit', edit_thing_path(@thing) %>
		<% end -%>
		<% if can? :destroy, @thing -%>
			<%= link_to 'Delete', @thing, :confirm => 'Are you sure?', :method => :delete %>
		<% end -%>
	</div>
	
	<h1 class="title"><%= @thing.title %></h1>
	
	<div class="description grid_12">
		<%=format_user_text @thing.description %>
	</div>

<% if @thing.images.any? -%>
		<h2>Media</h2>
		<p>
			<% @thing.images.each do |image| -%>
				<%= gallery_image_link_tag image.data.url(:thumb), image.data.url(:large),
				  :alt => "<b>#{image.title}</b><br />#{image.description}" %>
			<% end -%>
		</p>
		<% end -%>


<% content_for :sidebar do %>
	<div id="entry-people" class="entry-meta">			
		<h2>People</h2>
		<p>
			<% for_unique_people @thing do |person, role| -%>
				<%= link_to person.full_name, person_path(person) %> – <%= role %><br />
			<% end -%>
		</p>
	</div>
	
	<% if @thing.study_modules.present? -%>
	<div id="entry-study" class="entry-meta">
		
		<h2>Study</h2>
		<p>
			<%= comma_separated_links_for @thing.study_modules, :name %>
		</p>
	</div>
	<% end -%>

	<div id="entry-form" class="entry-meta">
	<h2>Form</h2>
	
		<p><%= @thing.kind %></p>
	
		<p><%= @thing.materials %></p>
	
		<p><%= @thing.dimensions %>
		<% if @thing.dimensions_additional.present? -%>
		(<%= @thing.dimensions_additional %>)
		<% end -%></p>
	
		<% if @thing.tools.any? -%>
		<p>Made with <%= @thing.tools.to_sentence %></p>
		<% end -%>
	</div> <!-- end #entry-form -->

	<% if @thing.release_date.present? -%>
	<div id="entry-time" class="entry-meta">
		<h2>Time</h2>
		<p>
		    Released: <%= @thing.release_date.strftime '%d.%m.%Y' %><br />
		  <% end -%>
		  <% if @thing.start_date.present? -%>
		    <small>Started: <%= @thing.start_date.strftime '%d.%m.%Y' %><small><br />
	  
		</p>
	</div> <!-- end #entry-time -->
	<% end -%>
	
<% end -%>