config/routes.rb
Katalog::Application.routes.draw do |map|
  resources :thing_lists

  resources :departments

  devise_for :users,
    :path_names => { :sign_up => 'register', :sign_in => 'log_in' },
    :controllers => { :registrations => "users/registrations" }
  
  resources :things, :people, :groups, :kontexts, :study_modules
  
  match '/:id', :to => 'things#show'
  
  root :to => "things#index"
end

app/models/thing_list.rb
class ThingList < ActiveRecord::Base
  has_many :thing_list_items, :order => 'position'
end

app/controllers/thing_lists_controller.rb
class ThingListsController < ApplicationController
  
  # layout nil, :only => [:show]
  
  # GET /thing_lists
  # GET /thing_lists.xml
  def index
    @thing_lists = ThingList.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @thing_lists }
    end
  end

  # GET /thing_lists/1
  # GET /thing_lists/1.xml
  def show
    @thing_list = ThingList.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @thing_list }
    end
  end

  # GET /thing_lists/new
  # GET /thing_lists/new.xml
  def new
    @thing_list = ThingList.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @thing_list }
    end
  end

  # GET /thing_lists/1/edit
  def edit
    @thing_list = ThingList.find(params[:id])
  end

  # POST /thing_lists
  # POST /thing_lists.xml
  def create
    @thing_list = ThingList.new(params[:thing_list])

    respond_to do |format|
      if @thing_list.save
        format.html { redirect_to(@thing_list, :notice => 'Thing list was successfully created.') }
        format.xml  { render :xml => @thing_list, :status => :created, :location => @thing_list }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @thing_list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /thing_lists/1
  # PUT /thing_lists/1.xml
  def update
    @thing_list = ThingList.find(params[:id])

    respond_to do |format|
      if @thing_list.update_attributes(params[:thing_list])
        format.html { redirect_to(@thing_list, :notice => 'Thing list was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @thing_list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /thing_lists/1
  # DELETE /thing_lists/1.xml
  def destroy
    @thing_list = ThingList.find(params[:id])
    @thing_list.destroy

    respond_to do |format|
      format.html { redirect_to(thing_lists_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/thing_lists_helper.rb
module ThingListsHelper
end

app/views/thing_lists/_form.html.erb
<%= form_for(@thing_list) do |f| %>
  <% if @thing_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thing_list.errors.count, "error") %> prohibited this thing_list from being saved:</h2>

      <ul>
      <% @thing_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/thing_lists/edit.html.erb
<h1>Editing thing_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @thing_list %> |
<%= link_to 'Back', thing_lists_path %>

app/views/thing_lists/index.html.erb
<h1>Listing thing_lists</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @thing_lists.each do |thing_list| %>
  <tr>
    <td><%= thing_list.title %></td>
    <td><%= link_to 'Show', thing_list %></td>
    <td><%= link_to 'Edit', edit_thing_list_path(thing_list) %></td>
    <td><%= link_to 'Destroy', thing_list, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Thing list', new_thing_list_path %>

app/views/thing_lists/new.html.erb
<h1>New thing_list</h1>

<%= render 'form' %>

<%= link_to 'Back', thing_lists_path %>

app/views/thing_lists/show.html.erb
<p id="notice"><%= notice %></p>

<h2>List: <%= @thing_list.title %></h2>
  
<ul>
<% @thing_list.thing_list_items.each do |item| %>
	<li><%= item.thing.title %></li>
<% end -%>
</ul>


<%= link_to 'Edit', edit_thing_list_path(@thing_list) %> |
<%= link_to 'Back', thing_lists_path %>