config/routes.rb
Katalog::Application.routes.draw do |map|
  resources :thing_lists

  resources :departments

  devise_for :users,
    :path_names => { :sign_up => 'register', :sign_in => 'log_in' },
    :controllers => { :registrations => "users/registrations" }
  
  resources :things, :people, :groups, :kontexts, :study_modules
  
  match '/:id', :to => 'things#show'
  
  root :to => "things#index"
end

app/models/study_module.rb
class StudyModule < ActiveRecord::Base
  belongs_to :department
  has_and_belongs_to_many :things
  has_and_belongs_to_many :teachers, :class_name => 'Person'
  
  KINDS = %w{ Entwurf Fachkurs Fachmodul Kolloquium Kurs Projekt Projektmodul Seminar Tutorium Übung Vorlesung Werkmodul Workshop Sonstige }
  
  scope :asc, order('name')
end

app/controllers/study_modules_controller.rb
class StudyModulesController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  load_and_authorize_resource
  
  def index
    if params[:own] && user_signed_in?
      @study_modules = StudyModule.by_user(current_user).asc
    else
      @study_modules = StudyModule.asc
    end
  end
  
  def show
  end
  
  def new
  end
  
  def edit
  end
  
  def create
    if @study_module.save
      redirect_to @study_module, :notice => 'Study Module was successfully created.'
    else
      render :action => "new"
    end
  end
  
  def update
    if @study_module.update_attributes(params[:study_module])
      redirect_to @study_module, :notice => 'Study Module was successfully updated.'
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @study_module.destroy
    redirect_to study_modules_url, :notice => 'Study Module destroyed.'
  end
end

app/views/study_modules/_form.html.erb
<%= form_for @study_module do |f| %>
  <% if @study_module.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@study_module.errors.count, "error") %> prohibited this study module from being saved:</h2>

      <ul>
      <% @study.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  
  <div class="field">
    <%= f.label :kind %><br />
    <%= f.collection_select :kind, StudyModule::KINDS, :to_s, :humanize %>
  </div>

  <div class="field">
    <%= f.label :department_id %><br />
    <%= f.collection_select :department_id, Department.asc, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :teacher_ids, "Teachers" %><br />
    <%= f.collection_select :teacher_ids, Person.asc, :id, :full_name, { :selected => @study_module.teacher_ids }, { :multiple => true, :name => 'study_module[teacher_ids][]' } -%>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/study_modules/edit.html.erb
<h1>Edit study module</h1>

<%= render 'form' %>

app/views/study_modules/index.html.erb
<div id="controls">
	<% if can? :create, StudyModule -%>
		<%= link_to 'New study module', new_study_module_path %>
	<% end -%>
</div>

<h1>Study</h1>

<% @study_modules.each do |study_module| %>
	<p>
		<%= study_module.kind %>: 
		<%= link_to study_module.name, study_module %>

	</p>
<% end %>

app/views/study_modules/new.html.erb
<h1>New study module</h1>

<%= render 'form' %>

app/views/study_modules/show.html.erb
<div id="controls">
	<% if can? :update, @study_module -%>
		<%= link_to 'Edit', edit_study_module_path(@study_module) %>
	<% end -%>
	<% if can? :destroy, @study_module -%>
		<%= link_to 'Delete', @study_module, :confirm => 'Are you sure?', :method => :delete %>
	<% end -%>
</div>

<h1 class="title"><%= @study_module.kind %>: <%= @study_module.name %></h1>

<div class="description grid_12">
	<%=format_user_text @study_module.description %>
</div>

<% content_for :sidebar do -%>
	<h2>Department</h2>
	<p>
		<%= link_to @study_module.department.name, @study_module.department %>
		<% if @study_module.department.head_of_department.present? -%>,
		<%= link_to @study_module.department.head_of_department.full_name,
			@study_module.department.head_of_department %>
		<% end -%>
	</p>
	
	<% if @study_module.teachers.present? -%>
	<h2>Teachers</h2>
	<p>
		<%= comma_separated_links_for @study_module.teachers, :full_name %>
	</p>
	<% end -%>
	
	<% if @study_module.things.present? -%>
	<h2>Things</h2>
	<%= comma_separated_links_for @study_module.things, :title %>
	<% end -%>
<% end -%>