config/routes.rb
Katalog::Application.routes.draw do |map|
  resources :thing_lists

  resources :departments

  devise_for :users,
    :path_names => { :sign_up => 'register', :sign_in => 'log_in' },
    :controllers => { :registrations => "users/registrations" }
  
  resources :things, :people, :groups, :kontexts, :study_modules
  
  match '/:id', :to => 'things#show'
  
  root :to => "things#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # visitors
    can :read, :all
    
    # dummy user enables us to call functions like admin?
    user ||= User.new
    
    # logged in users
    # there already was a user, thus new_record? returns false
    unless user.new_record?
      can :create, Thing
      can [:update,:destroy], Thing do |thing|
        # things they own
        thing.user == user
      end
      
      can :create, Person
      can :update, Person do |person|
        # people they own
        person == user.person
      end
      
      can :create, Group
      can :update, Group do |group|
        # groups they are a member in
        # or groups they own
        group.people.include? user.person or
        group.user == user
      end
      can :destroy, Group do |group|
        # groups they own
        group.user == user
      end
      
      can :manage, StudyModule do |study_module|
        user.teacher?
      end
      
      # admins
      if user.admin?
        can :manage, :all
      end
    end
  end
end

app/models/context.rb
class Context < ActiveRecord::Base
  acts_as_tree :order => 'name'
  
  scope :root_elements, where(:parent_id.eq % nil)
end

app/models/credit.rb
class Credit < ActiveRecord::Base
  belongs_to :person
  belongs_to :thing
  
  validates_presence_of :person, :role
  
  attr_accessible :person_id, :role, :tools
end

app/models/department.rb
class Department < ActiveRecord::Base
  
  attr_accessor :head_of_department_id
  before_save do |department|
    department.head_of_department = Person.find_by_id(head_of_department_id)
  end
  
  has_many :study_modules
  has_one :head_of_department, :class_name => 'Person'
  
  scope :asc, order('name')
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships, :dependent => :destroy
  has_many :people, :through => :memberships
  accepts_nested_attributes_for :memberships, :allow_destroy => true
  
  has_many :images, :as => :imageable, :dependent => :destroy
  accepts_nested_attributes_for :images, :allow_destroy => true
  
  validates_associated :memberships, :images
  
  belongs_to :user
  
  validates_presence_of :name, :description
  validates_format_of :website_url, :with => %r{^((http|https)://)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?/.*)?$|^$}ix, :allow_nil => true
  
  attr_accessible :name, :description, :website_url, :images_attributes, :memberships_attributes
  
  scope :asc, order('name')
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :imageable, :polymorphic => true
  
  has_attached_file :data, :styles => {
    :thumb => "100x100#",
    :medium => "640x1200>",
    :large => "1200x1200>"
  }
  
  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 5.megabytes
  validates_attachment_content_type :data, :content_type => ['image/jpeg', 'image/png', 'image/gif']
end

app/models/kontext.rb
class Kontext < ActiveRecord::Base
  acts_as_nested_set :order => 'name'
  
  has_many :kontext_links
  has_many :kontextables, :through => :kontext_links
  
  has_many :things, :through => :kontext_links, :source => :thing,
                    :conditions => "kontext_links.kontextable_type = 'Thing'"
                    
  scope :root_elements, where( :parent_id.eq % 0 )
end

app/models/kontext_link.rb
class KontextLink < ActiveRecord::Base
  belongs_to :kontext
  belongs_to :kontextable, :polymorphic => true
  
  belongs_to :thing, :class_name => 'Thing', :foreign_key => 'kontextable_id'
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :person
  belongs_to :group
  
  validates_presence_of :person
  validates_uniqueness_of :person_id, :scope => :group_id
  
  attr_accessible :person_id
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :credits
  has_many :things, :through => :credits
  
  has_many :memberships, :dependent => :destroy
  has_many :groups, :through => :memberships
  
  belongs_to :user
  
  belongs_to :department
  
  has_and_belongs_to_many :teaching_assignments, :class_name => 'StudyModule'
  
  validates_presence_of :first_name, :last_name
  
  attr_accessible :first_name, :last_name, :motto, :institution
  
  scope :asc, order('last_name')
  scope :by_user, lambda { |user| where( :user_id.eq % user.id ) }
  
  def full_name 
    "#{first_name} #{last_name}"
  end
  
  def real?
    ! institution
  end
  
  def institution?
    institution
  end
  
  def study_modules
    StudyModule.joins(:things => :credits).where(:credits => :person_id.eq % self.id)
  end
end

app/models/study_module.rb
class StudyModule < ActiveRecord::Base
  belongs_to :department
  has_and_belongs_to_many :things
  has_and_belongs_to_many :teachers, :class_name => 'Person'
  
  KINDS = %w{ Entwurf Fachkurs Fachmodul Kolloquium Kurs Projekt Projektmodul Seminar Tutorium Übung Vorlesung Werkmodul Workshop Sonstige }
  
  scope :asc, order('name')
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  has_many :credits, :dependent => :destroy
  has_many :people, :through => :credits
  accepts_nested_attributes_for :credits, :allow_destroy => true
  
  has_many :images, :as => :imageable, :dependent => :destroy
  accepts_nested_attributes_for :images, :allow_destroy => true
  
  belongs_to :user
  
  has_many :kontext_links, :as => :kontextable
  has_many :kontexts, :through => :kontext_links
  
  has_many :thing_list_items
  
  has_and_belongs_to_many :study_modules
  
  validates_presence_of :title, :description, :credits, :kind, :materials, 
    :license, :release_date
  validates_associated :credits, :images
  
  attr_accessible :title, :description, :credits_attributes, :images_attributes,
    :kontext_ids, :license, :kind, :materials, :dimensions_x, :dimensions_y,
    :dimensions_z, :dimensions_unit, :dimensions_additional, :release_date, 
    :start_date, :study_module_ids
  
  def dimensions
    result = [dimensions_x, dimensions_y, dimensions_z].compact.join('×')
    result += " #{dimensions_unit}" if dimensions_unit.present?
    result if result.present?
  end
  
  def tools
    self.credits.map(&:tools).uniq
  end
  
  scope :asc, order('title')
  scope :by_user, lambda { |user| where( :user_id.eq % user.id ) }
end

app/models/thing_list.rb
class ThingList < ActiveRecord::Base
  has_many :thing_list_items, :order => 'position'
end

app/models/thing_list_item.rb
class ThingListItem < ActiveRecord::Base
  belongs_to :thing_list
  belongs_to :thing
  
  acts_as_list :scope => 'thing_list_id'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :registerable, :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable
  
  has_one :person
  accepts_nested_attributes_for :person
  
  has_many :things
  
  attr_accessible :email, :password, :password_confirmation, :username, :person_attributes
  
  validates :username, :presence => true, :uniqueness => true
  
  ROLES = %w{ student teacher }
  
  # Enable Login with username OR email
  def self.find_for_database_authentication(conditions={})
    input = conditions[:email].gsub(/[%_]/,'')
    self.where(:username.matches % input).limit(1).first ||
    self.where(:email.matches % input).limit(1).first
  end
  
  def owns_thing? (thing)
    thing.user == self
  end
  
  def owns_group? (group)
    group.members.include? self.person
  end
  
  def admin?
    self.admin
  end
  
  def teacher?
    self.role == 'teacher'
  end
  
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/kontexts_helper.rb
module KontextsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
  
  def for_unique_credits( person, &block )
    person.things.uniq.each do |thing|
      credits = person.credits.where(:thing_id.eq % thing.id)
      roles = credits.map(&:role).to_sentence
      if block_given?
        yield thing, roles
      else
        return
      end
    end
  end
end

app/helpers/things_helper.rb
module ThingsHelper
  
  def for_unique_people( thing, &block )
    thing.people.uniq.each do |person|
      credits = person.credits.where(:thing_id.eq % thing.id)
      roles = credits.map(&:role).to_sentence
      
      if block_given?
        yield person, roles
      else
        return
      end
    end
  end
  
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en" class="no-js">
<head>
  <meta charset="utf-8">

  <!-- www.phpied.com/conditional-comments-block-downloads/ -->
  <!--[if IE]><![endif]-->

  <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame 
       Remove this if you use the .htaccess -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>bau-ha.us | <%= controller.controller_name %> </title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!--  Mobile Viewport Fix
        j.mp/mobileviewport & davidbcalhoun.com/2010/viewport-metatag 
  device-width : Occupy full width of the screen in its current orientation
  initial-scale = 1.0 retains dimensions instead of zooming out if page height > device height
  maximum-scale = 1.0 retains dimensions instead of zooming in if page width < device width
  -->
  <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;">


  <!-- Place favicon.ico and apple-touch-icon.png in the root of your domain and delete these references -->
  <link rel="shortcut icon" href="/favicon.ico">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">


  <!-- CSS : implied media="all" -->
  <%= stylesheet_link_tag 'vollkorn', 'reset', '960_24', 'text', 'jquery.fancybox-1.3.1', 'katalog' %>
  <%= csrf_meta_tag %>

  <!-- For the less-enabled mobile browsers like Opera Mini 
  <link rel="stylesheet" media="handheld" href="css/handheld.css?v=1"> -->

 
  <!-- All JavaScript at the bottom, except for Modernizr which enables HTML5 elements & feature detects -->
  <%= javascript_include_tag 'modernizr-1.5.min' %>

</head>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->

<!--[if lt IE 7 ]> <body class="ie6"> <![endif]-->
<!--[if IE 7 ]>    <body class="ie7"> <![endif]-->
<!--[if IE 8 ]>    <body class="ie8"> <![endif]-->
<!--[if IE 9 ]>    <body class="ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <body> <!--<![endif]-->

<header class="container_24">

	<div class="grid_6">
		<div id="site-button">
			<a href="http://bau-ha.us/">
			<%= image_tag 'bau_haus-sitebutton-grey-23px.png', :id=>"site-img" %>
			</a>
		</div>
		<h1 id="site-title">
			<%= link_to 'Katalog', root_path %>
		</h1>
	</div>

	<div id="access" role="navigation" class="grid_12 menu">
		<ul>
			<li class="menu-item <%= 'menu-item-current' if controller_name == 'things' %>">
				<%= link_to 'Things', things_path %>
			</li>
			<li class="menu-item <%= 'menu-item-current' if controller_name == 'people' %>">
				<%= link_to 'People', people_path %>
			</li>
			<li class="menu-item <%= 'menu-item-current' if controller_name == 'study_modules' %>">
				<%= link_to 'Study', study_modules_path %>
			</li>
		</ul>
	</div>
	
	<div id="user" class="grid_6 menu">
		<% if user_signed_in? -%>
			<span>Hello, <span class="username"><%= link_to current_user.username, edit_user_registration_path %>!</span>
			<%= link_to 'Log out', destroy_user_session_path %></span> 
		<% else -%>
			<span><%= link_to 'Log in', new_user_session_path %> or
			<%= link_to 'Register', new_user_registration_path %> </span>
		<% end -%>
	</div>
	
</header> <!-- end header -->
<div class="clear"></div>

<div id="page" class="container_24">
	
	<div id="main" class="grid_18">
		<% flash.each do |name, msg| -%>
			<%= content_tag :div, msg, :class => "", :id => "flash_#{name}" %>
			<div class="clear"></div>
		<% end -%>
	
		<div class="entry">
			<%= yield %>
		</div>
		<div class="clear"></div>
	</div> <!-- end #main -->
	
	<div id="side" class="grid_6">
		<div id="side-content">
			<%= yield :sidebar %>
		</div><!-- end #side-content -->
	</div><!-- end #side -->
	
</div> <!-- end #page -->
<div class="clear"></div>
	
<!--
<footer class="container_24">
	
	<div id="footer-1" class="grid_24 footer">
	</div>
	
</footer>
--> <!-- end footer -->

  <!-- Javascript at the bottom for fast page loading -->

  <%= javascript_include_tag 'jquery-1.4.2.min', 'rails', 'jquery.mousewheel-3.0.2.pack', 'jquery.fancybox-1.3.1.pack', 'jquery.oembed-1.0.1', 'application' %>

  <!--[if lt IE 7 ]>
    <script src="js/dd_belatedpng.js?v=1"></script>
  <![endif]-->


  <!-- asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet 
       change the UA-XXXXX-X to be your site's ID -->
  <script>
   var _gaq = [['_setAccount', 'UA-XXXXX-X'], ['_trackPageview']];
   (function(d, t) {
    var g = d.createElement(t),
        s = d.getElementsByTagName(t)[0];
    g.async = true;
    g.src = '//www.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g, s);
   })(document, 'script');
  </script>
  
</body>
</html>

app/views/layouts/groups.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Groups: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
</head>
<body>

<p style="color: green"><%= notice %></p>

<%= yield %>

</body>
</html>

app/views/shared/_image_fields.html.erb
<p class="fields">
  <% unless f.object.new_record? -%>
    <%= image_tag f.object.data.url(:thumb), :rel => 'fancybox' %>
  <% else -%>
    <%= f.label :data, 'Image — ' %>
    <%= f.file_field :data %>
  <% end -%><br />
  <%= link_to_remove_fields 'remove', f %>
</p>